### ISSUE TITLE
Error: Couldn't find preset "stage-0" relative to directory

### ISSUE THREAD

**Issue by alexicum** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#21]
```
> webpack-react-redux-isomorphic-render-example@1.0.0 development:webserver e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example
> nodemon ./webserver/entry.js --watch ./webserver

(node:18936) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
[nodemon] 1.11.0
[nodemon] reading config e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\.git/**/* .nyc_output .sass-cache bower_components coverage e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\node_modules/**/* e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\.git/**/* node_modules/**/*
[nodemon] watching: e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\webserver/**/*
[nodemon] watching extensions: js,json
[nodemon] starting `node ./webserver/entry.js`
[nodemon] child pid: 1204
[nodemon] watching 2 files


Error: Couldn't find preset "stage-0" relative to directory "e:\\Work\\Projects\\GitHub\\webpack-react-redux-isomorphic-render-example\\node_modules\\react-isomorphic-render"
    at e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\node_modules\babel-register\lib\node.js:103:45)
    at loader (e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (e:/Work/Projects/GitHub/webpack-react-redux-isomorphic-render-example/client/build/server/server.js:531:18)
    at __webpack_require__ (e:/Work/Projects/GitHub/webpack-react-redux-isomorphic-render-example/client/build/server/server.js:21:30)
From previous event:
    at server (e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\node_modules\universal-webpack\source\server.js:20:43)
    at Object.<anonymous> (e:/Work/Projects/GitHub/webpack-react-redux-isomorphic-render-example/client/rendering-service/start.js:7:1)
    at Module._compile (module.js:570:32)
    at loader (e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (e:\Work\Projects\GitHub\webpack-react-redux-isomorphic-render-example\client\rendering-service\entry.js:22:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

Web server is listening
Now go to http://localhost:3000
[nodemon] app crashed - waiting for file changes before starting...
Hash: a7c4a9c88a74397b53bf
Version: webpack 2.2.1
Time: 12510ms
                                    Asset     Size  Chunks                    Chunk Names
     9059f094ddb49c2b0fa6a254a6ebf2ad.jpg  40.2 kB          [emitted]
             main.a7c4a9c88a74397b53bf.js  3.44 MB       0  [emitted]  [big]  main
main-02755ea0d7a42f73bbff951d64336830.css  28.2 kB       0  [emitted]         main
webpack built a7c4a9c88a74397b53bf in 12510ms

```

After installing:
`npm i babel-preset-stage-0 --S`

it's showing:

> Error: e:/Work/Projects/GitHub/webpack-react-redux-isomorphic-render-example/node_modules/renderkid/node_modules/utila/scripts/js/lib/utila.js: No element indexed by 5
>     at ArraySet_at [as at]

**Comment by catamphetamine** [comment]
> No element indexed by 5 at ArraySet_at

I was too getting the same error on windows.
Didn't investigate it.

**Comment by catamphetamine** [comment]
As for `stage-0`: this project doesn't use it at all

https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example/search?utf8=%E2%9C%93&q=stage&type=Code

It only uses `stage-2`.
Why is babel searching for `stage-0` - that's probably a Windows Babel bug.

**Comment by catamphetamine** [comment]
So this `renderkid` package is a CLI tool which explains why it might be a Windows-specific error.
https://www.npmjs.com/package/renderkid

You could report this issue in their repo
https://github.com/AriaMinaei/RenderKid

But the project has been abandoned long time ago and it's not even known who exactly uses this package (babel, webpack, npm, etc)

**Comment by catamphetamine** [comment]
You could post your `e:/Work/Projects/GitHub/webpack-react-redux-isomorphic-render-example/client/build/server/server.js` though (assuming you HAVEN'T CHANGED ANYTHING SINCE THEN)

**Comment by catamphetamine** [comment]
The error about the preset is being thrown here:
https://github.com/babel/babel/blob/7.0/packages/babel-core/src/transformation/file/options/option-manager.js#L267

And you could also add `console.log()` in `node_modules` for this file
https://github.com/babel/babel/blob/7.0/packages/babel-core/src/transformation/file/options/option-manager.js#L175

**Comment by catamphetamine** [comment]
So why is it even searching for `stage-0`.
Maybe on windows it doesn't resolve the `.babelrc` correctly and instead reads configuration from some other `.babelrc` where `stage-0` is required.

**Comment by alexicum** [comment]
Hi, thank you for pointing!

> As for stage-0: this project doesn't use it at all

react-isomorphic-render using stage-0, but I don't know how it is breaking babel.
May be something related with cache [babel-register](https://babeljs.io/docs/usage/babel-register/#environment-variables).
So I will try to post issue on babel.

**Comment by alexicum** [comment]
> No element indexed by 5 at ArraySet_at

> But the project has been abandoned long time ago and it's not even known who exactly uses this package (babel, webpack, npm, etc)

RenderKid is used by [pretty-error](https://github.com/AriaMinaei/pretty-error)
and pretty-error is used by [print-error](https://github.com/halt-hammerzeit/print-error)

Here is full error description. 
```
Error: [Projects]/webpack-react-redux-isomorphic-render-example/node_modules/renderkid/node_modules/utila/scripts/js/lib/utila.js: No element indexed by 5
    at ArraySet_at [as at] ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\source-map\lib\array-set.js:92:9)
    at SourceMapConsumer.<anonymous> ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\source-map\lib\source-map-consumer.js:143:67)
    at Array.map (native)
    at SourceMapConsumer_eachMapping [as eachMapping] ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\source-map\lib\source-map-consumer.js:142:14)
    at [Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\index.js:465:26
    at File.mergeSourceMap ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\index.js:490:8)
    at File.generate ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\index.js:729:25)
    at File.transform ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\index.js:564:17)
    at [Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\pipeline.js:50:19
    at File.wrap ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\index.js:574:16)
    at Pipeline.transform ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\pipeline.js:47:17)
    at Object.transformFileSync ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\api\node.js:152:10)
    at compile ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-register\lib\node.js:118:20)
    at loader ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-register\lib\node.js:154:7)
From previous event:
    at server ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\universal-webpack\source\server.js:20:43)
    at Object.<anonymous> ([Projects]/webpack-react-redux-isomorphic-render-example/client/rendering-service/start.js:7:1)
    at Module._compile (module.js:570:32)
    at loader ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([Projects]\webpack-react-redux-isomorphic-render-example\client\rendering-service\entry.js:22:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by catamphetamine** [comment]
Ok, so `react-isomorphic-render` has `.babelrc` inside itself
https://unpkg.com/react-isomorphic-render@10.1.10/
Maybe that's the issue and maybe this file should be removed from the package.
Try to uninstall `stage-0` and remove `.babelrc` from `node_modules/react-isomorphic-render` and see it the `stage-0` error disappears.

**Comment by halt-hammerzeit** [comment]
Can you post this line from `server.js`

> From previous event:
    at server ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\universal-webpack\source\server.js:20:43)

**Comment by catamphetamine** [comment]
The error of `No element indexed by 5` is not caused by `print-error` most likely : it's just being output by it.
The real cause seems to be the `source-map` package which in turn means that source maps might be wrong (on Windows).
The `source-map` package is used by Babel:
https://github.com/babel/babel/search?utf8=%E2%9C%93&q=source-map
Babel is used by `babel-register` on the server side.

> `at server ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\universal-webpack\source\server.js:20:43)`

Why is it even trying to compile `source/server.js`.
It shouldn't be there.

**Comment by catamphetamine** [comment]
I deleted the `source` folder from `universal-webpack`.
Try installing the latest version and see if it throws.
Also install the latest `react-isomorphic-render`.

**Comment by catamphetamine** [comment]
Also seems that `pretty-error` is broken now in many places so I'm dropping it for now in favour of native Node.js `error.stack`

https://github.com/AriaMinaei/pretty-error/issues/40
https://github.com/AriaMinaei/RenderKid/issues/7

Install the latest version of `print-error`

**Comment by alexicum** [comment]
stage-0 resolved!

But pretty-error is still inside print-error and error is the same: `No element indexed by 5`
Could you remove import of pretty-error from print-error?

**Comment by catamphetamine** [comment]
Try the newest version of `print-error`

**Comment by alexicum** [comment]
The Fifth Element killed! )

Now:

```
ReferenceError: [BABEL] [Projects]\webpack-react-redux-isomorphic-render-example\node_modules\disposables\modules\index.js: Using removed Babel 5 option: base.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:220:20)
    at OptionManager.init ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at Object.transformFileSync ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-core\lib\api\node.js:152:10)
    at compile ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-register\lib\node.js:118:20)
    at loader ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([Projects]/webpack-react-redux-isomorphic-render-example/node_modules/react-dnd/lib/decorateHandler.js:19:20)
From previous event:
    at server ([Projects]\webpack-react-redux-isomorphic-render-example\node_modules\universal-webpack\source\server.js:20:43)
```

**Comment by catamphetamine** [comment]
Well, there you have it:
https://unpkg.com/disposables@1.0.1/
It has `.babelrc` in the npm package.
Tell him to add it to `.npmignore` and release a new version
https://github.com/gaearon/disposables/issues

**Comment by alexicum** [comment]
Thank you for your help, Nikolay!
Removed it manually for now and it works!!!
