### ISSUE TITLE
Cannot import css files within node_modules

### ISSUE THREAD

**Issue by Naddiseo** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#23]
I'm not sure which package this bug report belongs to, and I'd be happy to file it under the correct package if you point me in the right direction.

Steps to reproduce.
1. git clone https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example.git
2. cd webpack-react-redux-isomorphic-render-example/
3. npm install
4. npm install sweetalert
5. edit client/src/pages/Home.js, and add "import swstyles from 'sweetalert/dist/sweetalert.css';"
5. npm run dev

**Comment by catamphetamine** [comment]
Define " Cannot import css files within node_modules "

**Comment by Naddiseo** [comment]
It causes a syntax error because it doesn't seem to go through correct loaders.

```

SyntaxError: Unexpected token {
/tmp/webpack-react-redux-isomorphic-render-example/node_modules/sweetalert/dist/sweetalert.css:1
(function (exports, require, module, __filename, __dirname) { body.stop-scrolling {
                                                                                  ^
SyntaxError: Unexpected token {
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/tmp/webpack-react-redux-isomorphic-render-example/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.Object.defineProperty.value (/tmp/webpack-react-redux-isomorphic-render-example/client/build/server/webpack:/external "sweetalert/dist/sweetalert.css":1:1)
    at __webpack_require__ (/tmp/webpack-react-redux-isomorphic-render-example/client/build/server/webpack:/webpack/bootstrap 32f0507021615d6953ec:19:1)
    at Object.<anonymous> (/tmp/webpack-react-redux-isomorphic-render-example/client/build/server/server.js:819:89)
    at __webpack_require__ (/tmp/webpack-react-redux-isomorphic-render-example/client/build/server/webpack:/webpack/bootstrap 32f0507021615d6953ec:19:1)
    at Object.<anonymous> (/tmp/webpack-react-redux-isomorphic-render-example/client/build/server/server.js:1569:70)
    at __webpack_require__ (/tmp/webpack-react-redux-isomorphic-render-example/client/build/server/webpack:/webpack/bootstrap 32f0507021615d6953ec:19:1)
From previous event:
    at server (/tmp/webpack-react-redux-isomorphic-render-example/node_modules/universal-webpack/source/server.js:20:43)
    at Object.<anonymous> (/tmp/webpack-react-redux-isomorphic-render-example/client/rendering-service/start.js:7:1)
    at Module._compile (module.js:571:32)
    at loader (/tmp/webpack-react-redux-isomorphic-render-example/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/tmp/webpack-react-redux-isomorphic-render-example/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/webpack-react-redux-isomorphic-render-example/client/rendering-service/entry.js:22:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)

```

**Comment by catamphetamine** [comment]
Which it should because there is `.css` loader defined in `webpack.config.js` and it's not restricted to `src`.
So I'm closing this for now.
