### ISSUE TITLE
SyntaxError: Block-scoped declarations

### ISSUE THREAD

**Issue by gbishop** [halt-hammerzeit/webpack-react-redux-isomorphic-render-example#6]
When I npm run dev I get a ton of errors like this:

/home/gb/tmp/webpack-react-redux-isomorphic-render-example/code/common/server entry.js:30
                let folder = path.dirname(relative_path)
                ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/gb/tmp/webpack-react-redux-isomorphic-render-example/code/api-server/entry.js:1:63)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
[nodemon] app crashed - waiting for file changes before starting...

I'm a newb so I'm likely doing something wrong.

**Comment by catamphetamine** [comment]
Should be fixed now, pull the latest changes and try again

**Comment by gbishop** [comment]
Thanks! Working now.
